# Data Cleaning

In this notebook I focus on cleaning my datasets. Here I will deal with:
- Removing unrelated columns
- Removing repeated subtotal and sub-header rows
- Converting null values based on what is relative to them
- Removing problem rows with null values
- Setting minimum requirements for the datasets
- Setting column values to int and float where necessary
- Grouping each dataset by player name
- Resetting the index for each dataset

In [1]:
#####
# - IMPORTS
#####

import pandas as pd

In [2]:
#####
# - LOADING DATASETS & SETTING IT SO THAT ALL COLUMNS SHOW WHEN VIEWING THE DATASETS
#####

batting = pd.read_csv('scraped_batting.csv',index_col=0)
pitching = pd.read_csv('scraped_pitching.csv',index_col=0)

pd.set_option('display.max_columns', None)

In [3]:
batting

,Rk,Name,Age,Tm,Lg,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Pos Summary,Year
0,1,Henry Aaron,36,ATL,NL,150,598,516,103,154,26,1,38,118,9,0,74,63,.298,.385,.574,.958,149,296,13,2,0,6,15,*9H3,1970
1,2,Tommie Aaron,30,ATL,NL,44,66,63,3,13,2,0,2,7,0,0,3,10,.206,.242,.333,.576,50,21,5,0,0,0,0,H37/9,1970
2,3,Ted Abernathy,37,TOT,MLB,58,20,17,1,3,0,0,0,2,0,0,0,7,.176,.176,.176,.353,-2,3,0,0,3,0,0,1,1970
3,8,Ed Acosta#,26,PIT,NL,3,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,/1,1970
4,9,Jerry Adair,33,KCR,AL,7,33,27,0,4,0,0,0,1,0,1,5,3,.148,.281,.148,.429,23,4,1,0,1,0,1,/4,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50882,985,Jared Young*,26,CHC,NL,6,22,19,2,5,2,0,0,0,1,0,3,7,.263,.364,.368,.732,108,7,0,0,0,0,0,/D3H9,2022
50883,986,Seby Zavala,28,CHW,AL,61,205,178,22,48,14,0,2,21,0,0,19,64,.270,.347,.382,.729,107,68,1,3,3,2,0,2/H3D,2022
50884,987,Bradley Zimmer*,29,TOT,MLB,109,218,105,18,13,5,0,2,5,3,2,5,45,.124,.207,.229,.435,25,24,0,6,1,0,0,8H/D9,2022
50885,992,Mike Zunino,31,TBR,AL,36,123,115,7,17,3,0,5,16,0,0,6,46,.148,.195,.304,.499,44,35,2,1,0,1,0,2/H,2022
50886,NaN,LgAvg per 600 PA,NaN,NaN,NaN,167,600,536,68,129,26,2,17,65,8,3,49,135,.241,.310,.392,.702,NaN,210,11,7,1,4,2,NaN,2022

In [4]:
pitching

,Rk,Name,Age,Tm,Lg,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
0,1,Ted Abernathy,37,TOT,MLB,10,3,.769,2.60,58,0,37,0,0,14,83.0,65,31,24,3,55,5,59,5,0,3,366,152,3.85,1.446,7.0,0.3,6.0,6.4,1.07,1970
1,6,Ed Acosta,26,PIT,NL,0,0,NaN,13.50,3,0,2,0,0,1,2.2,5,4,4,1,2,0,1,1,0,0,16,33,10.14,2.625,16.9,3.4,6.8,3.4,0.50,1970
2,7,Hank Aguirre*,39,CHC,NL,3,0,1.000,4.50,17,0,3,0,0,1,14.0,13,10,7,3,9,1,11,1,0,0,64,102,6.00,1.571,8.4,1.9,5.8,7.1,1.22,1970
3,8,Jack Aker,29,NYY,AL,4,2,.667,2.06,41,0,28,0,0,16,70.0,57,19,16,3,20,5,36,4,0,1,284,173,3.20,1.100,7.3,0.4,2.6,4.6,1.80,1970
4,9,Lloyd Allen,20,CAL,AL,1,1,.500,2.63,8,2,0,0,0,0,24.0,23,7,7,0,11,2,12,1,0,2,102,140,3.14,1.417,8.6,0.0,4.1,4.5,1.09,1970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28736,1076,Rob Zastryzny*,30,TOT,MLB,0,0,NaN,6.75,6,0,1,0,0,0,4.0,3,4,3,0,1,0,3,0,0,1,16,70,2.36,1.000,6.8,0.0,2.3,6.8,3.00,2022
28737,1079,Angel Zerpa*,22,KCR,AL,2,1,.667,1.64,3,2,0,0,0,0,11.0,9,3,2,2,3,0,3,0,0,1,44,258,5.75,1.091,7.4,1.6,2.5,2.5,1.00,2022
28738,1080,T.J. Zeuch,26,CIN,NL,0,3,.000,15.19,3,3,0,0,0,0,10.2,24,18,18,5,7,0,5,3,0,0,64,30,11.08,2.906,20.3,4.2,5.9,4.2,0.71,2022
28739,1081,Bruce Zimmermann*,27,BAL,AL,2,5,.286,5.99,15,13,1,0,0,0,73.2,97,52,49,21,12,0,49,2,0,1,320,67,6.06,1.480,11.9,2.6,1.5,6.0,4.08,2022
28740,NaN,LgAvg per 180 IP,NaN,NaN,NaN,10,10,.497,4.02,90,20,21,0,0,5,180,167,88,80,22,63,2,171,9,1,7,763,100,3.98,1.276,8.3,1.1,3.1,8.5,2.72,2022

In [5]:
#####
# - LOOKING UP THE 'POS SUMMARY" COLUMN AS I WAS RECEIVING AN ERROR THAT IT DID NOT EXIST WHEN TRYING TO REMOVE IT
##### 

batting.columns[-2]

'Pos\xa0Summary'

In [6]:
#####
# - DROPPING IRRELEVANT COLUMNS
#####

batting.drop(['Rk', 'Lg', 'Pos\xa0Summary'], axis=1, inplace=True)
pitching.drop(['Rk', 'Lg'], axis=1, inplace=True)
#'Unnamed: 0',

In [7]:
batting.head(20)

,Name,Age,Tm,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Year
0,Henry Aaron,36,ATL,150,598,516,103,154,26,1,38,118,9,0,74,63,.298,.385,.574,.958,149,296,13,2,0,6,15,1970
1,Tommie Aaron,30,ATL,44,66,63,3,13,2,0,2,7,0,0,3,10,.206,.242,.333,.576,50,21,5,0,0,0,0,1970
2,Ted Abernathy,37,TOT,58,20,17,1,3,0,0,0,2,0,0,0,7,.176,.176,.176,.353,-2,3,0,0,3,0,0,1970
3,Ed Acosta#,26,PIT,3,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1970
4,Jerry Adair,33,KCR,7,33,27,0,4,0,0,0,1,0,1,5,3,.148,.281,.148,.429,23,4,1,0,1,0,1,1970
5,Tommie Agee,27,NYM,153,696,636,107,182,30,7,24,75,31,15,55,156,.286,.344,.469,.812,116,298,11,2,1,2,3,1970
6,Hank Aguirre,39,CHC,17,2,2,0,0,0,0,0,0,0,0,0,2,.000,.000,.000,.000,-100,0,0,0,0,0,0,1970
7,Jack Aker,29,NYY,41,17,16,0,1,0,0,0,1,0,0,0,6,.063,.063,.063,.125,-65,1,1,0,1,0,0,1970
8,Luis Alcaraz,29,KCR,35,127,120,10,20,5,1,1,14,0,0,4,13,.167,.192,.250,.442,22,30,2,0,1,1,0,1970
9,Bernie Allen*,31,WSA,104,305,261,31,61,7,1,8,29,0,2,43,21,.234,.342,.360,.702,99,94,4,0,1,0,4,1970
10,Dick Allen,28,STL,122,533,459,88,128,17,5,34,101,5,4,71,118,.279,.377,.560,.937,146,257,9,2,0,1,16,1970
11,Hank Allen,29,TOT,50,112,99,7,22,6,0,0,8,0,1,12,14,.222,.304,.283,.586,65,28,2,0,0,1,1,1970
12,Lloyd Allen,20,CAL,8,4,4,0,0,0,0,0,0,0,0,0,1,.000,.000,.000,.000,-100,0,0,0,0,0,0,1970
13,Gene Alley,29,PIT,121,466,426,46,104,16,5,8,41,7,3,31,70,.244,.297,.362,.659,78,154,6,3,2,4,9,1970
14,Bob Allison,35,MIN,47,87,72,15,15,5,0,1,7,1,0,14,20,.208,.345,.319,.664,83,23,2,1,0,0,0,1970
15,Sandy Alomar#,26,CAL,162,735,672,82,169,18,2,2,36,35,12,49,65,.251,.302,.293,.596,68,197,7,1,11,2,2,1970
16,Felipe Alou,35,OAK,154,618,575,70,156,25,3,8,55,10,5,32,31,.271,.308,.367,.675,88,211,13,1,4,6,6,1970
17,Jesus Alou,28,HOU,117,487,458,59,140,27,3,1,44,3,2,21,15,.306,.335,.384,.719,96,176,15,1,3,4,4,1970
18,Matty Alou*,31,PIT,155,718,677,97,201,21,8,1,47,19,11,30,18,.297,.329,.356,.685,87,241,9,4,4,3,3,1970
19,Name,Age,Tm,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,1970

In [8]:
pitching.head(20)

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
0,Ted Abernathy,37,TOT,10,3,.769,2.60,58,0,37,0,0,14,83.0,65,31,24,3,55,5,59,5,0,3,366,152,3.85,1.446,7.0,0.3,6.0,6.4,1.07,1970
1,Ed Acosta,26,PIT,0,0,NaN,13.50,3,0,2,0,0,1,2.2,5,4,4,1,2,0,1,1,0,0,16,33,10.14,2.625,16.9,3.4,6.8,3.4,0.50,1970
2,Hank Aguirre*,39,CHC,3,0,1.000,4.50,17,0,3,0,0,1,14.0,13,10,7,3,9,1,11,1,0,0,64,102,6.00,1.571,8.4,1.9,5.8,7.1,1.22,1970
3,Jack Aker,29,NYY,4,2,.667,2.06,41,0,28,0,0,16,70.0,57,19,16,3,20,5,36,4,0,1,284,173,3.20,1.100,7.3,0.4,2.6,4.6,1.80,1970
4,Lloyd Allen,20,CAL,1,1,.500,2.63,8,2,0,0,0,0,24.0,23,7,7,0,11,2,12,1,0,2,102,140,3.14,1.417,8.6,0.0,4.1,4.5,1.09,1970
5,Steve Arlin,24,SDP,1,0,1.000,2.84,2,2,0,1,1,0,12.2,11,4,4,0,8,0,3,0,0,0,56,144,4.06,1.500,7.8,0.0,5.7,2.1,0.38,1970
6,Gerry Arrigo*,29,CHW,0,3,.000,12.83,5,3,1,0,0,0,13.1,24,20,19,4,9,1,12,0,0,1,72,30,6.76,2.475,16.2,2.7,6.1,8.1,1.33,1970
7,Rick Austin*,23,CLE,2,5,.286,4.79,31,8,7,1,1,3,67.2,74,36,36,10,26,6,53,3,0,1,298,82,4.28,1.478,9.8,1.3,3.5,7.0,2.04,1970
8,Stan Bahnsen,25,NYY,14,11,.560,3.33,36,35,0,6,2,0,232.2,227,100,86,23,75,4,116,2,0,3,977,106,3.92,1.298,8.8,0.9,2.9,4.5,1.55,1970
9,Jack Baldschun,33,SDP,1,0,1.000,10.13,12,0,8,0,0,0,13.1,24,15,15,2,4,1,12,0,0,0,70,40,3.69,2.100,16.2,1.4,2.7,8.1,3.00,1970
10,Dave Baldwin,32,MIL,2,1,.667,2.55,28,0,16,0,0,1,35.1,25,11,10,4,18,6,26,0,0,0,144,149,4.17,1.217,6.4,1.0,4.6,6.6,1.44,1970
11,Steve Barber*,32,TOT,0,2,.000,6.20,10,2,6,0,0,0,20.1,27,16,14,3,11,3,14,1,0,3,97,72,4.95,1.869,12.0,1.3,4.9,6.2,1.27,1970
12,Steve Barber,22,MIN,0,0,NaN,4.61,18,0,10,0,0,2,27.1,26,14,14,1,18,2,14,2,0,4,125,83,4.28,1.610,8.6,0.3,5.9,4.6,0.78,1970
13,Fred Beene,27,BAL,0,0,NaN,6.00,4,0,1,0,0,0,6.0,8,5,4,1,5,4,4,0,0,0,31,65,5.97,2.167,12.0,1.5,7.5,6.0,0.80,1970
14,Mel Behney*,22,CIN,0,2,.000,4.50,5,1,1,0,0,0,10.0,15,11,5,1,8,2,2,0,0,0,52,96,5.94,2.300,13.5,0.9,7.2,1.8,0.25,1970
15,Bo Belinsky*,33,CIN,0,0,NaN,4.50,3,0,1,0,0,0,8.0,10,6,4,0,6,0,6,0,0,3,40,97,3.39,2.000,11.3,0.0,6.8,6.8,1.00,1970
16,Frank Bertaina*,26,STL,1,2,.333,3.16,8,5,1,0,0,0,31.1,36,16,11,1,15,3,14,0,0,3,142,132,3.60,1.628,10.3,0.3,4.3,4.0,0.93,1970
17,Jack Billingham,27,HOU,13,9,.591,3.98,46,24,7,8,2,0,187.2,190,102,83,10,63,2,134,10,0,11,818,98,3.07,1.348,9.1,0.5,3.0,6.4,2.13,1970
18,Wade Blasingame*,26,HOU,3,3,.500,3.48,13,13,0,1,0,0,77.2,76,34,30,4,23,3,55,2,0,4,320,113,2.86,1.275,8.8,0.5,2.7,6.4,2.39,1970
19,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,1970

In [9]:
#####
# - REMOVING REPEATED HEADER ROWS THEN CONFIRMING THEY HAVE BEEN REMOVED
#####

batting = batting[batting['Name'].str.contains('Name') == False]
pitching = pitching[pitching['Name'].str.contains('Name') == False]

In [10]:
batting.head(20)

,Name,Age,Tm,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Year
0,Henry Aaron,36,ATL,150,598,516,103,154,26,1,38,118,9,0,74,63,.298,.385,.574,.958,149,296,13,2,0,6,15,1970
1,Tommie Aaron,30,ATL,44,66,63,3,13,2,0,2,7,0,0,3,10,.206,.242,.333,.576,50,21,5,0,0,0,0,1970
2,Ted Abernathy,37,TOT,58,20,17,1,3,0,0,0,2,0,0,0,7,.176,.176,.176,.353,-2,3,0,0,3,0,0,1970
3,Ed Acosta#,26,PIT,3,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1970
4,Jerry Adair,33,KCR,7,33,27,0,4,0,0,0,1,0,1,5,3,.148,.281,.148,.429,23,4,1,0,1,0,1,1970
5,Tommie Agee,27,NYM,153,696,636,107,182,30,7,24,75,31,15,55,156,.286,.344,.469,.812,116,298,11,2,1,2,3,1970
6,Hank Aguirre,39,CHC,17,2,2,0,0,0,0,0,0,0,0,0,2,.000,.000,.000,.000,-100,0,0,0,0,0,0,1970
7,Jack Aker,29,NYY,41,17,16,0,1,0,0,0,1,0,0,0,6,.063,.063,.063,.125,-65,1,1,0,1,0,0,1970
8,Luis Alcaraz,29,KCR,35,127,120,10,20,5,1,1,14,0,0,4,13,.167,.192,.250,.442,22,30,2,0,1,1,0,1970
9,Bernie Allen*,31,WSA,104,305,261,31,61,7,1,8,29,0,2,43,21,.234,.342,.360,.702,99,94,4,0,1,0,4,1970
10,Dick Allen,28,STL,122,533,459,88,128,17,5,34,101,5,4,71,118,.279,.377,.560,.937,146,257,9,2,0,1,16,1970
11,Hank Allen,29,TOT,50,112,99,7,22,6,0,0,8,0,1,12,14,.222,.304,.283,.586,65,28,2,0,0,1,1,1970
12,Lloyd Allen,20,CAL,8,4,4,0,0,0,0,0,0,0,0,0,1,.000,.000,.000,.000,-100,0,0,0,0,0,0,1970
13,Gene Alley,29,PIT,121,466,426,46,104,16,5,8,41,7,3,31,70,.244,.297,.362,.659,78,154,6,3,2,4,9,1970
14,Bob Allison,35,MIN,47,87,72,15,15,5,0,1,7,1,0,14,20,.208,.345,.319,.664,83,23,2,1,0,0,0,1970
15,Sandy Alomar#,26,CAL,162,735,672,82,169,18,2,2,36,35,12,49,65,.251,.302,.293,.596,68,197,7,1,11,2,2,1970
16,Felipe Alou,35,OAK,154,618,575,70,156,25,3,8,55,10,5,32,31,.271,.308,.367,.675,88,211,13,1,4,6,6,1970
17,Jesus Alou,28,HOU,117,487,458,59,140,27,3,1,44,3,2,21,15,.306,.335,.384,.719,96,176,15,1,3,4,4,1970
18,Matty Alou*,31,PIT,155,718,677,97,201,21,8,1,47,19,11,30,18,.297,.329,.356,.685,87,241,9,4,4,3,3,1970
20,Luis Alvarado,21,BOS,59,196,183,19,41,11,0,1,10,1,2,9,30,.224,.258,.301,.558,49,55,5,0,2,2,2,1970

In [11]:
pitching.head(20)

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
0,Ted Abernathy,37,TOT,10,3,.769,2.60,58,0,37,0,0,14,83.0,65,31,24,3,55,5,59,5,0,3,366,152,3.85,1.446,7.0,0.3,6.0,6.4,1.07,1970
1,Ed Acosta,26,PIT,0,0,NaN,13.50,3,0,2,0,0,1,2.2,5,4,4,1,2,0,1,1,0,0,16,33,10.14,2.625,16.9,3.4,6.8,3.4,0.50,1970
2,Hank Aguirre*,39,CHC,3,0,1.000,4.50,17,0,3,0,0,1,14.0,13,10,7,3,9,1,11,1,0,0,64,102,6.00,1.571,8.4,1.9,5.8,7.1,1.22,1970
3,Jack Aker,29,NYY,4,2,.667,2.06,41,0,28,0,0,16,70.0,57,19,16,3,20,5,36,4,0,1,284,173,3.20,1.100,7.3,0.4,2.6,4.6,1.80,1970
4,Lloyd Allen,20,CAL,1,1,.500,2.63,8,2,0,0,0,0,24.0,23,7,7,0,11,2,12,1,0,2,102,140,3.14,1.417,8.6,0.0,4.1,4.5,1.09,1970
5,Steve Arlin,24,SDP,1,0,1.000,2.84,2,2,0,1,1,0,12.2,11,4,4,0,8,0,3,0,0,0,56,144,4.06,1.500,7.8,0.0,5.7,2.1,0.38,1970
6,Gerry Arrigo*,29,CHW,0,3,.000,12.83,5,3,1,0,0,0,13.1,24,20,19,4,9,1,12,0,0,1,72,30,6.76,2.475,16.2,2.7,6.1,8.1,1.33,1970
7,Rick Austin*,23,CLE,2,5,.286,4.79,31,8,7,1,1,3,67.2,74,36,36,10,26,6,53,3,0,1,298,82,4.28,1.478,9.8,1.3,3.5,7.0,2.04,1970
8,Stan Bahnsen,25,NYY,14,11,.560,3.33,36,35,0,6,2,0,232.2,227,100,86,23,75,4,116,2,0,3,977,106,3.92,1.298,8.8,0.9,2.9,4.5,1.55,1970
9,Jack Baldschun,33,SDP,1,0,1.000,10.13,12,0,8,0,0,0,13.1,24,15,15,2,4,1,12,0,0,0,70,40,3.69,2.100,16.2,1.4,2.7,8.1,3.00,1970
10,Dave Baldwin,32,MIL,2,1,.667,2.55,28,0,16,0,0,1,35.1,25,11,10,4,18,6,26,0,0,0,144,149,4.17,1.217,6.4,1.0,4.6,6.6,1.44,1970
11,Steve Barber*,32,TOT,0,2,.000,6.20,10,2,6,0,0,0,20.1,27,16,14,3,11,3,14,1,0,3,97,72,4.95,1.869,12.0,1.3,4.9,6.2,1.27,1970
12,Steve Barber,22,MIN,0,0,NaN,4.61,18,0,10,0,0,2,27.1,26,14,14,1,18,2,14,2,0,4,125,83,4.28,1.610,8.6,0.3,5.9,4.6,0.78,1970
13,Fred Beene,27,BAL,0,0,NaN,6.00,4,0,1,0,0,0,6.0,8,5,4,1,5,4,4,0,0,0,31,65,5.97,2.167,12.0,1.5,7.5,6.0,0.80,1970
14,Mel Behney*,22,CIN,0,2,.000,4.50,5,1,1,0,0,0,10.0,15,11,5,1,8,2,2,0,0,0,52,96,5.94,2.300,13.5,0.9,7.2,1.8,0.25,1970
15,Bo Belinsky*,33,CIN,0,0,NaN,4.50,3,0,1,0,0,0,8.0,10,6,4,0,6,0,6,0,0,3,40,97,3.39,2.000,11.3,0.0,6.8,6.8,1.00,1970
16,Frank Bertaina*,26,STL,1,2,.333,3.16,8,5,1,0,0,0,31.1,36,16,11,1,15,3,14,0,0,3,142,132,3.60,1.628,10.3,0.3,4.3,4.0,0.93,1970
17,Jack Billingham,27,HOU,13,9,.591,3.98,46,24,7,8,2,0,187.2,190,102,83,10,63,2,134,10,0,11,818,98,3.07,1.348,9.1,0.5,3.0,6.4,2.13,1970
18,Wade Blasingame*,26,HOU,3,3,.500,3.48,13,13,0,1,0,0,77.2,76,34,30,4,23,3,55,2,0,4,320,113,2.86,1.275,8.8,0.5,2.7,6.4,2.39,1970
20,Steve Blass,28,PIT,10,12,.455,3.52,31,31,0,6,1,0,196.2,187,92,77,14,73,8,120,5,1,2,824,111,3.53,1.322,8.6,0.6,3.3,5.5,1.64,1970

In [12]:
#####
# - FIGURING OUT WHY I AM GETTING TypeError: '>' not supported between instances of 'str' and 'int'
#####

batting['G'].dtype

dtype('O')

In [13]:
#####
# - CONVERTING COLUMN TYPES NEEDED TO REMOVE IRRELEVANT ROWS PRIOR TO WORKING ON NULL VALUES
#####

batting = batting.astype({'G': int,'AB': int,})
pitching = pitching.astype({'G': int, 'ERA' : float})

In [14]:
#####
# - COLLECTING ALL LEAGUE AVERAGE DATA TO BE ABLE TO CALCULATE AVG ERA OF DATASET
#####
lg_avg_era = pitching[pitching['Name'].str.contains('LgAvg per 180 IP') == True]

lg_avg_era.head(3)

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
364,LgAvg per 180 IP,NaN,NaN,10,10,.497,3.92,56,19,17,4,1,5,180,174,88,78,18,71,8,115,4,1,7,773,100,3.91,1.365,8.7,0.9,3.6,5.7,1.61,1970
709,LgAvg per 180 IP,NaN,NaN,10,10,.499,3.48,51,20,15,5,1,4,180,169,78,70,15,65,7,108,4,1,6,760,100,3.48,1.300,8.4,0.7,3.3,5.4,1.66,1971
1050,LgAvg per 180 IP,NaN,NaN,10,10,.497,3.31,51,20,15,5,2,4,180,165,75,66,14,64,8,111,4,1,6,755,99,3.30,1.270,8.2,0.7,3.2,5.6,1.74,1972

In [15]:
#####
# - CALCULATING LEAGUE AVERAGE ERA FROM 1970 - 2022
#####

league_avg = lg_avg_era['ERA'].mean()
league_avg = round(league_avg, 2)
league_avg

4.11

In [16]:
pitching.isna().sum()

Name       0
Age       53
Tm        53
W          0
L          0
W-L%    4437
ERA        9
G          0
GS         0
GF         0
CG         0
SHO        0
SV         0
IP         0
H          0
R          0
ER         0
HR         0
BB         0
IBB        0
SO         0
HBP        0
BK         0
WP         0
BF         0
ERA+     766
FIP       34
WHIP      34
H9        34
HR9       34
BB9       34
SO9       34
SO/W     794
Year       0
dtype: int64

In [17]:
#####
# - REMOVING LEAGUE AVERAGE ROWS AS THEY ARE NO LONGER NEEDED AND WERE PRODUCING NULL VALUES UNDER NAME AND TM
#####
pitching = pitching[pitching['Name'].str.contains('LgAvg per 180 IP') == False]

In [18]:
pitching.isna().sum()

Name       0
Age        0
Tm         0
W          0
L          0
W-L%    4437
ERA        9
G          0
GS         0
GF         0
CG         0
SHO        0
SV         0
IP         0
H          0
R          0
ER         0
HR         0
BB         0
IBB        0
SO         0
HBP        0
BK         0
WP         0
BF         0
ERA+     766
FIP       34
WHIP      34
H9        34
HR9       34
BB9       34
SO9       34
SO/W     794
Year       0
dtype: int64

In [19]:
#####
# - SETTING GAMES PLAYED MINIMUM TO 15 FOR BATTING DATASET AND 5 TO PITCHING DATASET
# - REMOVING PLAYERS SHOWING 0 AB ALONG WITH REPEATED FOOTER ROWS SHOWING NAN VALUES
# - SETTING NAN WL% PLAYERS TO 0 AS THAT REPRESENTS MANY PITCHERS WHO PLAYED ENOUGH GAMES BUT NOT IN THAT SITUATION
# - THERE WERE 53 NULL VALUES AFTER SETTING MINIMUM FOR BATTERS, BUT THEY WERE ALL TIED TO SUBTOTAL COLUMNS SO I JUST
#   REMOVED THEM
#####
batting = batting[batting['G'] > 14]
batting = batting[batting['AB'] > 1]
batting.dropna(inplace=True)

pitching = pitching[pitching['G'] > 4]
pitching['W-L%'] = pitching['W-L%'].fillna(0)

### BELOW NOT VALID AS IT WOULD DVIDE 4.11 BY 0 CAUSING FLOAT INFINITE###
#pitching['ERA+'] = pitching['ERA+'].fillna((100*(league_avg / pitching.ERA)))

In [20]:
pitching.isna().sum()

Name     0
Age      0
Tm       0
W        0
L        0
W-L%     0
ERA      0
G        0
GS       0
GF       0
CG       0
SHO      0
SV       0
IP       0
H        0
R        0
ER       0
HR       0
BB       0
IBB      0
SO       0
HBP      0
BK       0
WP       0
BF       0
ERA+    90
FIP      0
WHIP     0
H9       0
HR9      0
BB9      0
SO9      0
SO/W    72
Year     0
dtype: int64

In [21]:
#####
# - WHEN LOOKING AT THE DATA (NOT DISPLAYED IN THIS NOTEBOOK) I NOTICED THAT INF VALUES IN ERA+ LOOKED TO BE 
#   RELATED TO A 0.00 ERA SO I AM CHECKING TO SEE IF THEY ARE RELATED AND AFTER REVIEW THEY SHOW TO BE RELATED
#####

era_na = pitching.loc[pitching['ERA'] == 0.00]

In [22]:
era_na

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
409,Mike Caldwell*,22,SDP,1,0,1.000,0.0,6,0,2,0,0,0,6.2,4,0,0,0,3,3,5,0,0,2,26,NaN,2.30,1.050,5.4,0.0,4.1,6.8,1.67,1971
666,Ed Sprague,25,CIN,1,0,1.000,0.0,7,0,1,0,0,0,11.0,8,2,0,0,1,0,7,0,0,1,43,NaN,1.45,0.818,6.5,0.0,0.8,5.7,7.00,1971
684,Wayne Twitchell,23,PHI,1,0,1.000,0.0,6,1,2,0,0,0,16.0,8,4,0,1,10,0,15,1,0,0,69,NaN,3.45,1.125,4.5,0.6,5.6,8.4,1.50,1971
845,Al Hrabosky*,22,STL,1,0,1.000,0.0,5,0,2,0,0,0,7.0,2,0,0,0,3,0,9,0,0,1,27,NaN,1.11,0.714,2.6,0.0,3.9,11.6,3.00,1972
1264,Don Newhauser,25,BOS,0,0,0,0.0,9,0,8,0,0,1,12.0,9,2,0,0,13,2,8,1,0,2,59,NaN,4.73,1.833,6.8,0.0,9.8,6.0,0.62,1973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27590,Oliver Pérez*,39,CLE,0,1,.000,0.0,5,0,3,0,0,0,3.2,5,1,0,0,1,1,4,0,0,0,18,NaN,1.81,1.636,12.3,0.0,2.5,9.8,4.00,2021
27837,Brad Wieck*,29,CHC,0,0,0,0.0,15,0,5,0,0,0,17.0,10,0,0,0,10,0,28,0,0,0,71,NaN,1.64,1.176,5.3,0.0,5.3,14.8,2.80,2021
28074,Sean Doolittle*,35,WSN,0,0,0,0.0,6,0,0,0,0,0,5.1,1,0,0,0,0,0,6,0,0,0,17,NaN,0.86,0.188,1.7,0.0,0.0,10.1,NaN,2022
28113,J.P. Feyereisen,29,TBR,4,0,1.000,0.0,22,2,3,0,0,1,24.1,7,1,0,0,5,0,25,0,0,0,86,NaN,1.67,0.493,2.6,0.0,1.8,9.2,5.00,2022
28155,Ken Giles,31,SEA,0,0,0,0.0,5,0,3,0,0,0,4.1,1,0,0,0,4,0,6,0,0,1,18,NaN,3.11,1.154,2.1,0.0,8.3,12.5,1.50,2022

In [23]:
#####
# - SINCE THE NUMBER OF NULL VALUES IN THE ERA+ COLUMN MATCHES THE NUMBER OF PLAYERS WITH A 0.00 ERA I WILL JUST 
#   REMOVE THOSE ROWS INSTEAD OF TRYING TO CALCUATE THEM AS IT PRODUCES FLOAT INFINITE VALUES.
#####

pitching = pitching[pitching['ERA'] != 0.0]

In [24]:
era_na = pitching.loc[pitching['ERA'] == 0.00]

In [25]:
era_na

Empty DataFrame
Columns: [Name, Age, Tm, W, L, W-L%, ERA, G, GS, GF, CG, SHO, SV, IP, H, R, ER, HR, BB, IBB, SO, HBP, BK, WP, BF, ERA+, FIP, WHIP, H9, HR9, BB9, SO9, SO/W, Year]
Index: []

In [26]:
pitching.isna().sum()

Name     0
Age      0
Tm       0
W        0
L        0
W-L%     0
ERA      0
G        0
GS       0
GF       0
CG       0
SHO      0
SV       0
IP       0
H        0
R        0
ER       0
HR       0
BB       0
IBB      0
SO       0
HBP      0
BK       0
WP       0
BF       0
ERA+     0
FIP      0
WHIP     0
H9       0
HR9      0
BB9      0
SO9      0
SO/W    62
Year     0
dtype: int64

In [27]:
#####
# - NOW I AM WORKING ON RESOLVING THE NULL VALUES IN THE SO/W COLUMN
#####

sow_na = pitching[pitching['SO/W'].isna()]

In [28]:
sow_na

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
781,Tom Dukes,29,CAL,0,1,.000,1.64,7,0,3,0,0,1,11.0,11,3,2,1,0,0,8,1,0,1,43,187,2.40,1.000,9.0,0.8,0.0,6.5,NaN,1972
3680,Jay Howell,24,CIN,0,0,0,13.50,5,0,1,0,0,0,3.1,8,5,5,0,0,0,1,1,0,0,19,30,3.05,2.400,21.6,0.0,0.0,2.7,NaN,1980
4352,Steve Crawford,24,BOS,1,0,1.000,2.00,5,0,4,0,0,0,9.0,14,3,2,0,0,0,2,0,0,0,41,225,2.27,1.556,14.0,0.0,0.0,2.0,NaN,1982
4579,Bill Scherrer*,24,CIN,0,1,.000,2.60,5,2,2,0,0,0,17.1,17,7,5,0,0,0,7,0,0,0,69,145,1.91,0.981,8.8,0.0,0.0,3.6,NaN,1982
4751,Jeff Dedmon,23,ATL,0,0,0,13.50,5,0,0,0,0,0,4.0,10,6,6,1,0,0,3,0,0,0,23,32,4.51,2.500,22.5,2.3,0.0,6.8,NaN,1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27735,Gabe Speier*,26,KCR,0,0,0,1.17,7,0,1,0,0,0,7.2,10,3,1,0,0,0,5,1,0,0,33,404,2.26,1.304,11.7,0.0,0.0,5.9,NaN,2021
27990,Drew Carlton,26,DET,0,0,0,2.08,5,0,4,0,0,0,8.2,4,4,2,1,0,0,7,0,0,1,32,190,3.00,0.462,4.2,1.0,0.0,7.3,NaN,2022
28116,Jake Fishman*,27,MIA,0,0,0,4.09,7,0,2,0,0,0,11.0,13,5,5,0,0,0,6,3,0,0,48,102,2.84,1.182,10.6,0.0,0.0,4.9,NaN,2022
28607,Cody Stashak,28,MIN,3,0,1.000,3.86,11,0,4,0,0,0,16.1,16,7,7,1,0,0,15,0,0,0,65,102,2.07,0.980,8.8,0.6,0.0,8.3,NaN,2022
28715,Justin Wilson*,34,CIN,0,1,.000,2.45,5,0,0,0,0,0,3.2,3,1,1,0,0,0,7,0,0,0,13,199,-0.71,0.818,7.4,0.0,0.0,17.2,NaN,2022

In [29]:
#####
# - RUNNING INTO ANOTHER ISSUE WITH DIVIDING BY 0. 
# - SINCE THIS RATIO IS USED TO DISPLAY HOW MANY STRIKEOUTS PER WALK AND THEY ARE ALL SHOWING TO HAVE 0 WALKS 
#   I WILL CONVERT THIS COLUMN TO MATCH THEIR SO COLUMN
#####

pitching['SO/W'] = pitching['SO/W'].fillna(pitching['SO'])

In [30]:
sow_na = pitching[pitching['SO/W'].isna()]

In [31]:
sow_na

Empty DataFrame
Columns: [Name, Age, Tm, W, L, W-L%, ERA, G, GS, GF, CG, SHO, SV, IP, H, R, ER, HR, BB, IBB, SO, HBP, BK, WP, BF, ERA+, FIP, WHIP, H9, HR9, BB9, SO9, SO/W, Year]
Index: []

In [32]:
pitching.isna().sum()

Name    0
Age     0
Tm      0
W       0
L       0
W-L%    0
ERA     0
G       0
GS      0
GF      0
CG      0
SHO     0
SV      0
IP      0
H       0
R       0
ER      0
HR      0
BB      0
IBB     0
SO      0
HBP     0
BK      0
WP      0
BF      0
ERA+    0
FIP     0
WHIP    0
H9      0
HR9     0
BB9     0
SO9     0
SO/W    0
Year    0
dtype: int64

In [33]:
batting.dtypes

Name    object
Age     object
Tm      object
G        int64
PA      object
AB       int64
R       object
H       object
2B      object
3B      object
HR      object
RBI     object
SB      object
CS      object
BB      object
SO      object
BA      object
OBP     object
SLG     object
OPS     object
OPS+    object
TB      object
GDP     object
HBP     object
SH      object
SF      object
IBB     object
Year     int64
dtype: object

In [34]:
pitching.dtypes

Name     object
Age      object
Tm       object
W        object
L        object
W-L%     object
ERA     float64
G         int64
GS       object
GF       object
CG       object
SHO      object
SV       object
IP       object
H        object
R        object
ER       object
HR       object
BB       object
IBB      object
SO       object
HBP      object
BK       object
WP       object
BF       object
ERA+     object
FIP      object
WHIP     object
H9       object
HR9      object
BB9      object
SO9      object
SO/W     object
Year      int64
dtype: object

In [35]:
#####
# - CONVERTING COLUMNS TO INT AND FLOATS
#####
batting = batting.astype({'Age': int,'PA': int,'R': int,'H': int,'2B': int,'3B': int,'HR': int,
                          'RBI': int,'SB': int,'CS': int,'BB': int,'SO': int,'BA': float,
                          'OBP': float,'SLG': float,'OPS': float,'OPS+': int,'TB': int,'GDP': int,
                          'HBP': int,'SH': int,'SF': int,'IBB': int,'Year': int})

pitching = pitching.astype({'Age': int,'W': int,'L': int,'W-L%': float,'G': int,'GS': int,
                            'GF': int,'CG': int,'SHO': int,'SV': int,'IP': float,'H': int,'R': int,
                            'ER': int,'HR': int,'BB': int,'IBB': int,'SO': int,'HBP': int,'BK': int,
                            'WP': int,'BF': int,'ERA+': int,'FIP': float,'WHIP': float,'H9': float,
                            'HR9': float,'BB9': float,'SO9': float,'SO/W': float,'Year': int})

In [36]:
batting.dtypes

Name     object
Age       int64
Tm       object
G         int64
PA        int64
AB        int64
R         int64
H         int64
2B        int64
3B        int64
HR        int64
RBI       int64
SB        int64
CS        int64
BB        int64
SO        int64
BA      float64
OBP     float64
SLG     float64
OPS     float64
OPS+      int64
TB        int64
GDP       int64
HBP       int64
SH        int64
SF        int64
IBB       int64
Year      int64
dtype: object

In [37]:
pitching.dtypes

Name     object
Age       int64
Tm       object
W         int64
L         int64
W-L%    float64
ERA     float64
G         int64
GS        int64
GF        int64
CG        int64
SHO       int64
SV        int64
IP      float64
H         int64
R         int64
ER        int64
HR        int64
BB        int64
IBB       int64
SO        int64
HBP       int64
BK        int64
WP        int64
BF        int64
ERA+      int64
FIP     float64
WHIP    float64
H9      float64
HR9     float64
BB9     float64
SO9     float64
SO/W    float64
Year      int64
dtype: object

In [38]:
batting.head()

,Name,Age,Tm,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Year
0,Henry Aaron,36,ATL,150,598,516,103,154,26,1,38,118,9,0,74,63,0.298,0.385,0.574,0.958,149,296,13,2,0,6,15,1970
1,Tommie Aaron,30,ATL,44,66,63,3,13,2,0,2,7,0,0,3,10,0.206,0.242,0.333,0.576,50,21,5,0,0,0,0,1970
2,Ted Abernathy,37,TOT,58,20,17,1,3,0,0,0,2,0,0,0,7,0.176,0.176,0.176,0.353,-2,3,0,0,3,0,0,1970
5,Tommie Agee,27,NYM,153,696,636,107,182,30,7,24,75,31,15,55,156,0.286,0.344,0.469,0.812,116,298,11,2,1,2,3,1970
6,Hank Aguirre,39,CHC,17,2,2,0,0,0,0,0,0,0,0,0,2,0.000,0.000,0.000,0.000,-100,0,0,0,0,0,0,1970

In [39]:
pitching.head()

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
0,Ted Abernathy,37,TOT,10,3,0.769,2.60,58,0,37,0,0,14,83.0,65,31,24,3,55,5,59,5,0,3,366,152,3.85,1.446,7.0,0.3,6.0,6.4,1.07,1970
2,Hank Aguirre*,39,CHC,3,0,1.000,4.50,17,0,3,0,0,1,14.0,13,10,7,3,9,1,11,1,0,0,64,102,6.00,1.571,8.4,1.9,5.8,7.1,1.22,1970
3,Jack Aker,29,NYY,4,2,0.667,2.06,41,0,28,0,0,16,70.0,57,19,16,3,20,5,36,4,0,1,284,173,3.20,1.100,7.3,0.4,2.6,4.6,1.80,1970
4,Lloyd Allen,20,CAL,1,1,0.500,2.63,8,2,0,0,0,0,24.0,23,7,7,0,11,2,12,1,0,2,102,140,3.14,1.417,8.6,0.0,4.1,4.5,1.09,1970
6,Gerry Arrigo*,29,CHW,0,3,0.000,12.83,5,3,1,0,0,0,13.1,24,20,19,4,9,1,12,0,0,1,72,30,6.76,2.475,16.2,2.7,6.1,8.1,1.33,1970

In [40]:
#####
# - GROUPING ALL THE PLAYERS TOGETHER AND FILTERING OUT ANY THAT HAVE LESS THAN 2 SEASONS OF DATA FOR BOTH DATASETS
#####

def group(batting):
    if batting.shape[0]!=1:
        return batting
batting = batting.groupby(['Name']).apply(group)

def group(pitching):
    if pitching.shape[0]!=1:
        return pitching
pitching = pitching.groupby(['Name']).apply(group)

In [41]:
batting.head(50)

                                    Name  Age   Tm    G   PA   AB    R    H  \
Name
A.J. Burnett     25733      A.J. Burnett   24  FLA   25   59   50    0    4
                 26858      A.J. Burnett   25  FLA   29   69   57    1    6
                 29095      A.J. Burnett   27  FLA   18   37   29    4    4
                 30219      A.J. Burnett   28  FLA   31   79   68    3   10
                 38346      A.J. Burnett   35  PIT   29   71   63    1    4
                 39537      A.J. Burnett   36  PIT   29   67   59    1    4
                 40745      A.J. Burnett   37  PHI   30   65   60    5    8
                 41970      A.J. Burnett   38  PIT   24   52   42    1    5
A.J. Ellis       36180        A.J. Ellis   29  LAD   44  128  108    6   30
                 37354        A.J. Ellis   30  LAD   31  103   85    8   23
                 38532        A.J. Ellis   31  LAD  133  505  423   44  114
                 39718        A.J. Ellis   32  LAD  115  448  390   43   93
                 40926        A.J. Ellis   33  LAD   93  347  283   21   54
                 42147        A.J. Ellis   34  LAD   63  217  181   24   43
                 43385        A.J. Ellis   35  TOT   64  196  171   11   37
                 44633        A.J. Ellis   36  MIA   51  163  143   17   30
                 45863        A.J. Ellis   37  SDP   66  183  151   19   41
A.J. Hinch       22689        A.J. Hinch   24  OAK  120  391  337   34   78
                 23809        A.J. Hinch   25  OAK   76  228  205   26   44
                 26032        A.J. Hinch   27  KCR   45  134  121   10   19
                 27159        A.J. Hinch   28  KCR   72  220  197   25   49
                 28278        A.J. Hinch   29  DET   27   82   74    7   15
A.J. Pierzynski* 25258  A.J. Pierzynski*   23  MIN   33   96   88   12   27
                 26397  A.J. Pierzynski*   24  MIN  114  407  381   51  110
                 27509  A.J. Pierzynski*   25  MIN  130  469  440   54  132
                 28619  A.J. Pierzynski*   26  MIN  137  533  487   63  152
                 29785  A.J. Pierzynski*   27  SFG  131  510  471   45  128
                 30910  A.J. Pierzynski*   28  CHW  128  497  460   61  118
                 32037  A.J. Pierzynski*   29  CHW  140  543  509   65  150
                 33214  A.J. Pierzynski*   30  CHW  136  509  472   54  124
                 34390  A.J. Pierzynski*   31  CHW  134  570  534   66  150
                 35553  A.J. Pierzynski*   32  CHW  138  535  504   57  151
                 36712  A.J. Pierzynski*   33  CHW  128  503  474   43  128
                 37881  A.J. Pierzynski*   34  CHW  129  500  464   38  133
                 39079  A.J. Pierzynski*   35  CHW  135  520  479   68  133
                 40270  A.J. Pierzynski*   36  TEX  134  529  503   48  137
                 41464  A.J. Pierzynski*   37  TOT  102  362  338   25   85
                 42709  A.J. Pierzynski*   38  ATL  113  436  407   38  122
                 43941  A.J. Pierzynski*   39  ATL   81  259  247   15   54
AJ Pollock       39085        AJ Pollock   24  ARI   31   93   81    8   20
                 40277        AJ Pollock   25  ARI  137  482  443   64  119
                 41472        AJ Pollock   26  ARI   75  287  265   41   80
                 42720        AJ Pollock   27  ARI  157  673  609  111  192
                 45184        AJ Pollock   29  ARI  112  466  425   73  113
                 46430        AJ Pollock   30  ARI  113  460  413   61  106
                 47719        AJ Pollock   31  LAD   86  342  308   49   82
                 48549        AJ Pollock   32  LAD   55  210  196   30   54
                 49689        AJ Pollock   33  LAD  117  422  384   53  114
                 50666        AJ Pollock   34  CHW  138  527  489   61  120
Aaron Altherr    41835     Aaron Altherr   24  PHI   39  161  137   25   33

                        2B  3B  HR  RBI  SB  CS  BB   SO     BA    OBP    SLG  \
Name
A.J. Burnett     25733   1   0   0    0   0   0   1   27  0.080  0.115  0.100
                 26858   2   0   1    3   0   0   5   28  0.105  0.177  0.193
                 29095   0   0   0    1   0   0   0   11  0.138  0.138  0.138
                 30219   2   2   1    2   0   0   1   34  0.147  0.171  0.279
                 38346   0   0   0    2   0   0   3   36  0.063  0.106  0.063
                 39537   0   0   0    2   0   0   2   33  0.068  0.098  0.068
                 40745   2   0   0    1   0   0   3   23  0.133  0.175  0.167
                 41970   0   0   1    5   0   0   0   20  0.119  0.116  0.190
A.J. Ellis       36180   5   0   0   16   0   0  14   18  0.278  0.363  0.324
                 37354   1   1   2   11   0   1  14   16  0.271  0.392  0.376
                 38532  20   1  13   52   0   0  65  107  0.270  0.373  0.414
                 39718  17   1  10   52   0   2  45   78  0.238  0.318  0.364
                 40926   9   0   3   25   0   0  53   57  0.191  0.323  0.254
                 42147   9   0   7   21   0   0  32   38  0.238  0.355  0.403
                 43385   8   0   2   22   2   1  19   31  0.216  0.301  0.298
                 44633   5   0   6   14   0   0  12   29  0.210  0.298  0.371
                 45863   8   0   1   15   0   0  26   37  0.272  0.378  0.344
A.J. Hinch       22689  10   0   9   35   3   0  30   89  0.231  0.296  0.341
                 23809   4   1   7   24   6   2  11   41  0.215  0.260  0.346
                 26032   3   0   6   15   1   1   8   26  0.157  0.226  0.331
                 27159   7   1   7   27   3   3  18   35  0.249  0.321  0.401
                 28278   3   1   3   11   0   0   3   18  0.203  0.247  0.392
A.J. Pierzynski* 25258   5   1   2   11   1   0   5   14  0.307  0.354  0.455
                 26397  33   2   7   55   1   7  16   57  0.289  0.322  0.441
                 27509  31   6   6   49   1   2  13   61  0.300  0.334  0.439
                 28619  35   3  11   74   3   1  24   55  0.312  0.360  0.464
                 29785  28   2  11   77   0   1  19   27  0.272  0.319  0.410
                 30910  21   0  18   56   0   2  23   68  0.257  0.308  0.420
                 32037  24   0  16   64   1   0  22   72  0.295  0.333  0.436
                 33214  24   0  14   50   1   1  25   66  0.263  0.309  0.403
                 34390  31   1  13   60   1   0  19   71  0.281  0.312  0.416
                 35553  22   1  13   49   1   1  24   52  0.300  0.331  0.425
                 36712  29   0   9   56   3   4  15   39  0.270  0.300  0.388
                 37881  29   1   8   48   0   0  23   33  0.287  0.323  0.405
                 39079  18   4  27   77   0   0  28   78  0.278  0.326  0.501
                 40270  24   1  17   70   1   1  11   76  0.272  0.297  0.425
                 41464  12   1   5   37   0   1  14   54  0.251  0.288  0.337
                 42709  24   1   9   49   0   2  19   37  0.300  0.339  0.430
                 43941  15   0   2   23   1   0   6   29  0.219  0.243  0.304
AJ Pollock       39085   4   1   2    8   1   2   9   11  0.247  0.315  0.395
                 40277  28   5   8   38  12   3  33   82  0.269  0.322  0.409
                 41472  19   6   7   24  14   3  19   46  0.302  0.353  0.498
                 42720  39   6  20   76  39   7  53   89  0.315  0.367  0.498
                 45184  33   6  14   49  20   6  35   71  0.266  0.330  0.471
                 46430  21   5  21   65  13   2  31  100  0.257  0.316  0.484
                 47719  15   1  15   47   5   1  23   74  0.266  0.327  0.468
                 48549   9   0  16   34   2   2  12   45  0.276  0.314  0.566
                 49689  27   1  21   69   9   1  30   80  0.297  0.355  0.536
                 50666  26   1  14   56   3   1  32   98  0.245  0.292  0.389
Aaron Altherr    41835  11   4   5   22   6   2  16   41  0.241  0.338  0.489

                          OPS  OPS+   TB  GDP  HBP  SH  SF  IBB  Year
Name
A.J. Burnett     25733  0.215   -42    5    0    1   7   0    0  2001
                 26858  0.370    -1   11    1    0   7   0    0  2002
                 29095  0.276   -26    4    1    0   8   0    0  2004
                 30219  0.451    19   19    1    1   9   0    0  2005
                 38346  0.170   -51    4    1    0   5   0    0  2012
                 39537  0.166   -52    4    2    0   6   0    0  2013
                 40745  0.341    -4   10    2    0   2   0    0  2014
                 41970  0.307   -17    8    1    0   9   1    0  2015
A.J. Ellis       36180  0.687    91   35    5    1   4   1    1  2010
                 37354  0.769   117   32    2    3   1   0    0  2011
                 38532  0.786   118  175   17    7   6   4   11  2012
                 39718  0.682    93  142   11    3   4   6    1  2013
                 40926  0.577    68   72   15    4   3   4    5  2014
                 42147  0.758   113   73    4    1   3   0    1  2015
                 43385  0.599    63   51    5    2   3   1    2  2016
                 44633  0.669    82   53    6    6   2   0    0  2017
                 45863  0.722   104   52    2    1   3   2    1  2018
A.J. Hinch       22689  0.638    69  115    6    4  13   7    0  1998
                 23809  0.607    58   71    4    2   9   1    0  1999
                 26032  0.556    41   40    5    3   1   1    1  2001
                 27159  0.722    84   79    2    3   2   0    0  2002
                 28278  0.639    71   29    3    2   1   2    0  2003
A.J. Pierzynski* 25258  0.809   100   40    1    2   0   1    0  2000
                 26397  0.763    98  168    7    4   1   3    4  2001
                 27509  0.773   104  193   14   11   2   3    1  2002
                 28619  0.824   115  226   13   15   2   5   12  2003
                 29785  0.729    86  193   27   15   2   3    4  2004
                 30910  0.728    90  193   13   12   1   1    5  2005
                 32037  0.769    94  222   10    8   3   1    6  2006
                 33214  0.712    83  190   21    8   1   3    5  2007
                 34390  0.728    89  222   14    8   3   6    5  2008
                 35553  0.755    93  214   18    1   3   3    6  2009
                 36712  0.688    84  184   17    6   6   2    2  2010
                 37881  0.728    94  188   19    5   2   6    6  2011
                 39079  0.827   120  240    8    8   1   4    5  2012
                 40270  0.722    95  214   14    9   0   6    2  2013
                 41464  0.625    75  114   13    5   1   4    2  2014
                 42709  0.769   112  175   19    7   0   3    2  2015
                 43941  0.547    46   75   13    3   0   3    1  2016
AJ Pollock       39085  0.710    90   32    2    0   1   2    1  2012
                 40277  0.730   100  181    5    2   3   1    1  2013
                 41472  0.851   134  132    4    2   1   0    0  2014
                 42720  0.865   130  303   19    2   0   9    0  2015
                 45184  0.801   100  200    8    6   0   0    1  2017
                 46430  0.800   108  200    6    8   1   7    2  2018
                 47719  0.795   107  144    7    7   0   4    1  2019
                 48549  0.881   132  111    6    0   0   2    1  2020
                 49689  0.892   134  206    4    6   0   2    4  2021
                 50666  0.681    91  190   13    2   0   4    0  2022
Aaron Altherr    41835  0.827   126   67    3    5   1   2    0  2015

In [42]:
pitching.head(50)

                            Name  Age   Tm   W   L   W-L%   ERA   G  GS  GF  \
Name
A.J. Achter  21667   A.J. Achter   25  MIN   1   0  1.000  3.27   7   0   1
             22359   A.J. Achter   26  MIN   0   1  0.000  6.75  11   0   4
             23094   A.J. Achter   27  LAA   1   0  1.000  3.11  27   0  17
A.J. Burnett 12222  A.J. Burnett   22  FLA   4   2  0.667  3.48   7   7   0
             12809  A.J. Burnett   23  FLA   3   7  0.300  4.79  13  13   0
             13415  A.J. Burnett   24  FLA  11  12  0.478  4.05  27  27   0
             14007  A.J. Burnett   25  FLA  12   9  0.571  3.30  31  29   0
             15241  A.J. Burnett   27  FLA   7   6  0.538  3.68  20  19   0
             15869  A.J. Burnett   28  FLA  12  12  0.500  3.44  32  32   0
             16474  A.J. Burnett   29  TOR  10   8  0.556  3.98  21  21   0
             17120  A.J. Burnett   30  TOR  10   8  0.556  3.75  25  25   0
             17790  A.J. Burnett   31  TOR  18  10  0.643  4.07  35  34   1
             18436  A.J. Burnett   32  NYY  13   9  0.591  4.04  33  33   0
             19096  A.J. Burnett   33  NYY  10  15  0.400  5.26  33  33   0
             19738  A.J. Burnett   34  NYY  11  11  0.500  5.15  33  32   0
             20399  A.J. Burnett   35  PIT  16  10  0.615  3.51  31  31   0
             21062  A.J. Burnett   36  PIT  10  11  0.476  3.30  30  30   0
             21745  A.J. Burnett   37  PHI   8  18  0.308  4.59  34  34   0
             22447  A.J. Burnett   38  PIT   9   7  0.563  3.18  26  26   0
A.J. Cole    23217     A.J. Cole   24  WSN   1   2  0.333  5.17   8   8   0
             23972     A.J. Cole   25  WSN   3   5  0.375  3.81  11   8   0
             24732     A.J. Cole   26  TOT   4   2  0.667  6.14  32   2  14
             25543     A.J. Cole   27  CLE   3   1  0.750  3.81  25   0   9
             26357     A.J. Cole   28  TOR   3   0  1.000  3.09  24   0   7
             27124     A.J. Cole   29  TOR   0   0  0.000  1.13   6   0   4
A.J. Griffin 20557  A.J. Griffin   24  OAK   7   1  0.875  3.06  15  15   0
             21225  A.J. Griffin   25  OAK  14  10  0.583  3.83  32  32   0
             23358  A.J. Griffin   28  TEX   7   4  0.636  5.07  23  23   0
             24111  A.J. Griffin   29  TEX   6   6  0.500  5.94  18  15   2
A.J. Minter* 24292  A.J. Minter*   23  ATL   0   1  0.000  3.00  16   0   3
             25071  A.J. Minter*   24  ATL   4   3  0.571  3.23  65   0  31
             25884  A.J. Minter*   25  ATL   3   4  0.429  7.06  36   0  12
             26683  A.J. Minter*   26  ATL   1   1  0.500  0.83  22   0   6
             27511  A.J. Minter*   27  ATL   3   6  0.333  3.78  61   0   4
             28395  A.J. Minter*   28  ATL   5   4  0.556  2.06  75   0  13
A.J. Puk*    25976     A.J. Puk*   24  OAK   2   0  1.000  3.18  10   0   0
             27614     A.J. Puk*   26  OAK   0   3  0.000  6.08  12   0   3
             28494     A.J. Puk*   27  OAK   4   3  0.571  3.12  62   0   9
A.J. Sager   9863     A.J. Sager   29  SDP   1   4  0.200  5.98  22   3   4
             10400    A.J. Sager   30  COL   0   0  0.000  7.36  10   0   2
             10936    A.J. Sager   31  DET   4   5  0.444  5.01  22   9   1
             11482    A.J. Sager   32  DET   3   4  0.429  4.18  38   1   8
             12020    A.J. Sager   33  DET   4   2  0.667  6.52  31   3   7
A.J. Schugel 22970  A.J. Schugel   26  ARI   0   0  0.000  5.00   5   0   2
             23701  A.J. Schugel   27  PIT   2   2  0.500  3.63  36   0  11
             24449  A.J. Schugel   28  PIT   4   0  1.000  1.97  32   0   4
AJ Ramos     20820      AJ Ramos   25  MIA   0   0  0.000  3.86  11   0   4
             21494      AJ Ramos   26  MIA   3   4  0.429  3.15  68   0  18
             22176      AJ Ramos   27  MIA   7   0  1.000  2.11  68   0  12
             22899      AJ Ramos   28  MIA   2   4  0.333  2.30  71   0  51

                    CG  SHO  SV     IP    H    R   ER  HR  BB  IBB   SO  HBP  \
Name
A.J. Achter  21667   0    0   0   11.0   14    7    4   2   3    0    5    0
             22359   0    0   0   13.1   12   10   10   4   6    1   14    0
             23094   0    0   0   37.2   43   13   13   7  12    1   14    1
A.J. Burnett 12222   0    0   0   41.1   37   23   16   3  25    2   33    0
             12809   0    0   0   82.2   80   46   44   8  44    3   57    2
             13415   2    1   0  173.1  145   82   78  20  83    3  128    7
             14007   7    5   0  204.1  153   84   75  12  90    5  203    9
             15241   1    0   0  120.0  102   50   49   9  38    0  113    4
             15869   4    2   0  209.0  184   97   80  12  79    1  198    7
             16474   2    1   0  135.2  138   67   60  14  39    3  118    8
             17120   2    0   0  165.2  131   74   69  23  66    2  176   12
             17790   1    0   0  221.1  211  109  100  19  86    2  231    9
             18436   1    0   0  207.0  193   99   93  25  97    0  195   10
             19096   1    0   0  186.2  204  118  109  25  78    2  145   19
             19738   0    0   0  190.1  190  115  109  31  83    2  173    9
             20399   1    1   0  202.1  189   86   79  18  62    1  180    9
             21062   1    0   0  191.0  165   79   70  11  67    3  209    9
             21745   1    0   0  213.2  205  122  109  20  96    2  190   16
             22447   0    0   0  164.0  174   64   58  11  49    2  143   11
A.J. Cole    23217   0    0   0   38.1   37   24   22   7  14    1   39    2
             23972   0    0   0   52.0   51   23   22   8  27    0   44    3
             24732   0    0   0   48.1   55   38   33  15  22    1   59    0
             25543   0    0   1   26.0   31   16   11   4   8    0   30    0
             26357   0    0   1   23.1   19    9    8   3   9    2   20    0
             27124   0    0   1    8.0    6    1    1   1   1    0    7    0
A.J. Griffin 20557   0    0   0   82.1   74   29   28  10  19    0   64    1
             21225   1    1   0  200.0  171   91   85  36  54    2  171    4
             23358   0    0   0  119.0  116   68   67  28  46    1  107    7
             24111   1    1   0   77.1   76   52   51  20  28    0   61    6
A.J. Minter* 24292   0    0   0   15.0   13    5    5   1   2    0   26    0
             25071   0    0  15   61.1   57   23   22   3  22    1   69    2
             25884   0    0   5   29.1   36   23   23   3  23    5   35    1
             26683   0    0   0   21.2   15    3    2   1   9    2   24    0
             27511   0    0   0   52.1   44   27   22   2  20    0   57    1
             28395   0    0   5   70.0   49   21   16   5  15    0   94    3
A.J. Puk*    25976   0    0   0   11.1   10    4    4   1   5    0   13    0
             27614   0    0   0   13.1   18    9    9   1   6    0   16    1
             28494   0    0   4   66.1   53   27   23   7  23    3   76   10
A.J. Sager   9863    0    0   0   46.2   62   34   31   4  16    5   26    2
             10400   0    0   0   14.2   19   16   12   1   7    1   10    0
             10936   0    0   0   79.0   91   46   44  10  29    2   52    2
             11482   0    0   3   84.0   81   43   39  10  24    6   53    1
             12020   0    0   2   59.1   79   47   43   7  23    4   23    1
A.J. Schugel 22970   0    0   0    9.0   17   13    5   2   5    2    5    0
             23701   0    0   1   52.0   41   22   21   4  13    0   46    1
             24449   0    0   0   32.0   31    8    7   3  14    2   27    0
AJ Ramos     20820   0    0   0    9.1    8    4    4   2   4    0   13    1
             21494   0    0   0   80.0   58   32   28   4  43    3   86    2
             22176   0    0   0   64.0   36   16   15   1  43    7   73    3
             22899   0    0  32   70.1   45   18   18   6  26    0   87    3

                    BK  WP   BF  ERA+   FIP   WHIP    H9  HR9  BB9   SO9  \
Name
A.J. Achter  21667   0   0   49   123  5.40  1.545  11.5  1.6  2.5   4.1
             22359   0   0   58    62  6.28  1.350   8.1  2.7  4.1   9.5
             23094   0   0  160   130  5.85  1.460  10.3  1.7  2.9   3.3
A.J. Burnett 12222   0   0  182   124  4.30  1.500   8.1  0.7  5.4   7.2
             12809   0   2  364    92  4.68  1.500   8.7  0.9  4.8   6.2
             13415   1   7  733   105  4.63  1.315   7.5  1.0  4.3   6.6
             14007   0  14  844   121  3.19  1.189   6.7  0.5  4.0   8.9
             15241   0   7  490   112  3.19  1.167   7.7  0.7  2.9   8.5
             15869   0  12  873   116  3.11  1.258   7.9  0.5  3.4   8.5
             16474   1   6  577   115  3.79  1.305   9.2  0.9  2.6   7.8
             17120   0   5  691   119  4.33  1.189   7.1  1.2  3.6   9.6
             17790   2  11  957   104  3.45  1.342   8.6  0.8  3.5   9.4
             18436   1  17  896   114  4.33  1.401   8.4  1.1  4.2   8.5
             19096   0  16  829    82  4.83  1.511   9.8  1.2  3.8   7.0
             19738   0  25  837    83  4.77  1.434   9.0  1.5  3.9   8.2
             20399   0  10  851   107  3.52  1.241   8.4  0.8  2.8   8.0
             21062   0  12  801   108  2.80  1.215   7.8  0.5  3.2   9.8
             21745   0   9  935    82  4.14  1.409   8.6  0.8  4.0   8.0
             22447   1   6  699   122  3.36  1.360   9.5  0.6  2.7   7.8
A.J. Cole    23217   0   1  168    83  4.74  1.330   8.7  1.6  3.3   9.2
             23972   1   2  229   118  5.20  1.500   8.8  1.4  4.7   7.6
             24732   0   2  221    69  6.12  1.593  10.2  2.8  4.1  11.0
             25543   0   0  118   125  3.83  1.500  10.7  1.4  2.8  10.4
             26357   0   3   95   144  4.31  1.200   7.3  1.2  3.5   7.7
             27124   0   0   30   413  3.42  0.875   6.8  1.1  1.1   7.9
A.J. Griffin 20557   0   0  336   127  3.85  1.130   8.1  1.1  2.1   7.0
             21225   0   7  823   101  4.55  1.125   7.7  1.6  2.4   7.7
             23358   1   0  509    90  5.74  1.361   8.8  2.1  3.5   8.1
             24111   0   2  338    81  6.26  1.345   8.8  2.3  3.3   7.1
A.J. Minter* 24292   0   0   60   148  0.96  1.000   7.8  0.6  1.2  15.6
             25071   0   5  260   127  2.72  1.288   8.4  0.4  3.2  10.1
             25884   0   5  147    66  4.61  2.011  11.0  0.9  7.1  10.7
             26683   0   1   85   570  2.82  1.108   6.2  0.4  3.7  10.0
             27511   2   0  221   115  2.69  1.223   7.6  0.3  3.4   9.8
             28395   0   3  271   198  2.13  0.914   6.3  0.6  1.9  12.1
A.J. Puk*    25976   0   2   47   139  3.39  1.324   7.9  0.8  4.0  10.3
             27614   0   2   65    70  3.32  1.800  12.2  0.7  4.1  10.8
             28494   1   6  281   120  3.68  1.146   7.2  0.9  3.1  10.3
A.J. Sager   9863    0   0  217    70  4.29  1.671  12.0  0.8  3.1   5.0
             10400   0   0   70    74  4.06  1.773  11.7  0.6  4.3   6.1
             10936   0   1  347   102  4.68  1.519  10.4  1.1  3.3   5.9
             11482   0   0  350   110  4.29  1.250   8.7  1.1  2.6   5.7
             12020   0   4  274    72  5.11  1.719  12.0  1.1  3.5   3.5
A.J. Schugel 22970   0   0   51    86  6.58  2.444  17.0  2.0  5.0   5.0
             23701   0   2  204   114  3.18  1.038   7.1  0.7  2.3   8.0
             24449   0   2  136   218  4.00  1.406   8.7  0.8  3.9   7.6
AJ Ramos     20820   0   0   40   110  4.70  1.286   7.7  1.9  3.9  12.5
             21494   0   1  338   123  3.24  1.263   6.5  0.5  4.8   9.7
             22176   0   7  270   177  3.21  1.234   5.1  0.1  6.0  10.3
             22899   0   2  277   166  3.01  1.009   5.8  0.8  3.3  11.1

                     SO/W  Year
Name
A.J. Achter  21667   1.67  2014
             22359   2.33  2015
             23094   1.17  2016
A.J. Burnett 12222   1.32  1999
             12809   1.30  2000
             13415   1.54  2001
             14007   2.26  2002
             15241   2.97  2004
             15869   2.51  2005
             16474   3.03  2006
             17120   2.67  2007
             17790   2.69  2008
             18436   2.01  2009
             19096   1.86  2010
             19738   2.08  2011
             20399   2.90  2012
             21062   3.12  2013
             21745   1.98  2014
             22447   2.92  2015
A.J. Cole    23217   2.79  2016
             23972   1.63  2017
             24732   2.68  2018
             25543   3.75  2019
             26357   2.22  2020
             27124   7.00  2021
A.J. Griffin 20557   3.37  2012
             21225   3.17  2013
             23358   2.33  2016
             24111   2.18  2017
A.J. Minter* 24292  13.00  2017
             25071   3.14  2018
             25884   1.52  2019
             26683   2.67  2020
             27511   2.85  2021
             28395   6.27  2022
A.J. Puk*    25976   2.60  2019
             27614   2.67  2021
             28494   3.30  2022
A.J. Sager   9863    1.63  1994
             10400   1.43  1995
             10936   1.79  1996
             11482   2.21  1997
             12020   1.00  1998
A.J. Schugel 22970   1.00  2015
             23701   3.54  2016
             24449   1.93  2017
AJ Ramos     20820   3.25  2012
             21494   2.00  2013
             22176   1.70  2014
             22899   3.35  2015

In [43]:
#####
# - REMOVING THE NEWLY CREATED INDEX LEVEL FROM THE DATASETS
#####

batting.index = batting.index.droplevel()
pitching.index = pitching.index.droplevel()

In [44]:
batting.head()

,Name,Age,Tm,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Year
25733,A.J. Burnett,24,FLA,25,59,50,0,4,1,0,0,0,0,0,1,27,0.080,0.115,0.100,0.215,-42,5,0,1,7,0,0,2001
26858,A.J. Burnett,25,FLA,29,69,57,1,6,2,0,1,3,0,0,5,28,0.105,0.177,0.193,0.370,-1,11,1,0,7,0,0,2002
29095,A.J. Burnett,27,FLA,18,37,29,4,4,0,0,0,1,0,0,0,11,0.138,0.138,0.138,0.276,-26,4,1,0,8,0,0,2004
30219,A.J. Burnett,28,FLA,31,79,68,3,10,2,2,1,2,0,0,1,34,0.147,0.171,0.279,0.451,19,19,1,1,9,0,0,2005
38346,A.J. Burnett,35,PIT,29,71,63,1,4,0,0,0,2,0,0,3,36,0.063,0.106,0.063,0.170,-51,4,1,0,5,0,0,2012

In [45]:
pitching.head()

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
21667,A.J. Achter,25,MIN,1,0,1.000,3.27,7,0,1,0,0,0,11.0,14,7,4,2,3,0,5,0,0,0,49,123,5.40,1.545,11.5,1.6,2.5,4.1,1.67,2014
22359,A.J. Achter,26,MIN,0,1,0.000,6.75,11,0,4,0,0,0,13.1,12,10,10,4,6,1,14,0,0,0,58,62,6.28,1.350,8.1,2.7,4.1,9.5,2.33,2015
23094,A.J. Achter,27,LAA,1,0,1.000,3.11,27,0,17,0,0,0,37.2,43,13,13,7,12,1,14,1,0,0,160,130,5.85,1.460,10.3,1.7,2.9,3.3,1.17,2016
12222,A.J. Burnett,22,FLA,4,2,0.667,3.48,7,7,0,0,0,0,41.1,37,23,16,3,25,2,33,0,0,0,182,124,4.30,1.500,8.1,0.7,5.4,7.2,1.32,1999
12809,A.J. Burnett,23,FLA,3,7,0.300,4.79,13,13,0,0,0,0,82.2,80,46,44,8,44,3,57,2,0,2,364,92,4.68,1.500,8.7,0.9,4.8,6.2,1.30,2000

In [46]:
#####
# - RESETTING THE BATTING INDEX SO IT REFLECTS THE NEW ORDER OF THE DATASET
#####

batting.reset_index(drop=True, inplace=True)

In [47]:
#####
# - RESETTING THE PITCHING INDEX SO IT REFLECTS THE NEW ORDER OF THE DATASET
#####

pitching.reset_index(drop=True, inplace=True)

In [48]:
batting

,Name,Age,Tm,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Year
0,A.J. Burnett,24,FLA,25,59,50,0,4,1,0,0,0,0,0,1,27,0.080,0.115,0.100,0.215,-42,5,0,1,7,0,0,2001
1,A.J. Burnett,25,FLA,29,69,57,1,6,2,0,1,3,0,0,5,28,0.105,0.177,0.193,0.370,-1,11,1,0,7,0,0,2002
2,A.J. Burnett,27,FLA,18,37,29,4,4,0,0,0,1,0,0,0,11,0.138,0.138,0.138,0.276,-26,4,1,0,8,0,0,2004
3,A.J. Burnett,28,FLA,31,79,68,3,10,2,2,1,2,0,0,1,34,0.147,0.171,0.279,0.451,19,19,1,1,9,0,0,2005
4,A.J. Burnett,35,PIT,29,71,63,1,4,0,0,0,2,0,0,3,36,0.063,0.106,0.063,0.170,-51,4,1,0,5,0,0,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31689,Ángel Pagán#,30,SFG,154,659,605,95,174,38,15,8,56,29,7,48,97,0.288,0.338,0.440,0.778,120,266,6,0,2,4,5,2012
31690,Ángel Pagán#,31,SFG,71,305,280,44,79,16,3,5,30,9,4,23,36,0.282,0.334,0.414,0.749,113,116,1,0,0,2,0,2013
31691,Ángel Pagán#,32,SFG,96,413,383,56,115,21,2,3,27,16,6,25,53,0.300,0.342,0.389,0.731,110,149,5,1,1,3,1,2014
31692,Ángel Pagán#,33,SFG,133,551,512,55,134,21,3,3,37,12,4,32,93,0.262,0.303,0.332,0.635,75,170,12,1,0,6,0,2015
31693,Ángel Pagán#,34,SFG,129,543,495,71,137,24,5,12,55,15,4,42,66,0.277,0.331,0.418,0.750,102,207,11,0,0,3,1,2016

In [49]:
pitching

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
0,A.J. Achter,25,MIN,1,0,1.000,3.27,7,0,1,0,0,0,11.0,14,7,4,2,3,0,5,0,0,0,49,123,5.40,1.545,11.5,1.6,2.5,4.1,1.67,2014
1,A.J. Achter,26,MIN,0,1,0.000,6.75,11,0,4,0,0,0,13.1,12,10,10,4,6,1,14,0,0,0,58,62,6.28,1.350,8.1,2.7,4.1,9.5,2.33,2015
2,A.J. Achter,27,LAA,1,0,1.000,3.11,27,0,17,0,0,0,37.2,43,13,13,7,12,1,14,1,0,0,160,130,5.85,1.460,10.3,1.7,2.9,3.3,1.17,2016
3,A.J. Burnett,22,FLA,4,2,0.667,3.48,7,7,0,0,0,0,41.1,37,23,16,3,25,2,33,0,0,0,182,124,4.30,1.500,8.1,0.7,5.4,7.2,1.32,1999
4,A.J. Burnett,23,FLA,3,7,0.300,4.79,13,13,0,0,0,0,82.2,80,46,44,8,44,3,57,2,0,2,364,92,4.68,1.500,8.7,0.9,4.8,6.2,1.30,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23611,Zane Smith*,33,PIT,10,8,0.556,3.27,25,24,0,2,1,0,157.0,162,67,57,18,34,7,57,0,0,2,645,132,4.55,1.248,9.3,1.0,1.9,3.3,1.68,1994
23612,Zane Smith*,34,BOS,8,8,0.500,5.61,24,21,0,0,0,0,110.2,144,78,69,7,23,1,47,1,1,0,484,87,3.73,1.509,11.7,0.6,1.9,3.8,2.04,1995
23613,Zane Smith*,35,PIT,4,6,0.400,5.08,16,16,0,1,1,0,83.1,104,53,47,7,21,4,47,4,1,0,368,87,4.04,1.500,11.2,0.8,2.3,5.1,2.24,1996
23614,Zeke Spruill,23,ARI,0,2,0.000,5.56,6,2,1,0,0,0,11.1,17,11,7,3,5,0,9,1,0,0,55,72,6.49,1.941,13.5,2.4,4.0,7.1,1.80,2013
23615,Zeke Spruill,24,ARI,1,1,0.500,3.57,6,1,1,0,0,0,22.2,27,11,9,0,4,0,14,1,0,0,99,106,2.56,1.368,10.7,0.0,1.6,5.6,3.50,2014

In [50]:
#####
# - CREATING FUNCTIONS TO SHOW THE STATS I WILL PREDICT FOR THE NEXT SEASON SO THAT I CAN COMPARE IT LATER TO
#   MY ML MODEL PREDICTION
#####

def nxt_batting(batter):
    batter = batter.sort_values('Year')
    batter['Nxt_BA'] = batter['BA'].shift(-1)
    batter['Nxt_RBI'] = batter['RBI'].shift(-1)
    batter['Nxt_HR'] = batter['HR'].shift(-1)
    batter['Nxt_BB'] = batter['BB'].shift(-1)
    batter['Nxt_SO'] = batter['SO'].shift(-1)
    return batter

batting = batting.groupby('Name').apply(nxt_batting)
                
def nxt_pitching(pitcher):
    pitcher = pitcher.sort_values('Year')
    pitcher['Nxt_ERA'] = pitcher['ERA'].shift(-1)
    pitcher['Nxt_SO'] = pitcher['SO'].shift(-1)
    pitcher['Nxt_WHIP'] = pitcher['WHIP'].shift(-1)
    pitcher['Nxt_BB'] = pitcher['BB'].shift(-1)
    pitcher['Nxt_W'] = pitcher['W'].shift(-1)
    pitcher['Nxt_SV'] = pitcher['SV'].shift(-1)
    return pitcher

pitching = pitching.groupby('Name').apply(nxt_pitching)

In [51]:
batting

,Name,Age,Tm,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Year,Nxt_BA,Nxt_RBI,Nxt_HR,Nxt_BB,Nxt_SO
0,A.J. Burnett,24,FLA,25,59,50,0,4,1,0,0,0,0,0,1,27,0.080,0.115,0.100,0.215,-42,5,0,1,7,0,0,2001,0.105,3.0,1.0,5.0,28.0
1,A.J. Burnett,25,FLA,29,69,57,1,6,2,0,1,3,0,0,5,28,0.105,0.177,0.193,0.370,-1,11,1,0,7,0,0,2002,0.138,1.0,0.0,0.0,11.0
2,A.J. Burnett,27,FLA,18,37,29,4,4,0,0,0,1,0,0,0,11,0.138,0.138,0.138,0.276,-26,4,1,0,8,0,0,2004,0.147,2.0,1.0,1.0,34.0
3,A.J. Burnett,28,FLA,31,79,68,3,10,2,2,1,2,0,0,1,34,0.147,0.171,0.279,0.451,19,19,1,1,9,0,0,2005,0.063,2.0,0.0,3.0,36.0
4,A.J. Burnett,35,PIT,29,71,63,1,4,0,0,0,2,0,0,3,36,0.063,0.106,0.063,0.170,-51,4,1,0,5,0,0,2012,0.068,2.0,0.0,2.0,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31689,Ángel Pagán#,30,SFG,154,659,605,95,174,38,15,8,56,29,7,48,97,0.288,0.338,0.440,0.778,120,266,6,0,2,4,5,2012,0.282,30.0,5.0,23.0,36.0
31690,Ángel Pagán#,31,SFG,71,305,280,44,79,16,3,5,30,9,4,23,36,0.282,0.334,0.414,0.749,113,116,1,0,0,2,0,2013,0.300,27.0,3.0,25.0,53.0
31691,Ángel Pagán#,32,SFG,96,413,383,56,115,21,2,3,27,16,6,25,53,0.300,0.342,0.389,0.731,110,149,5,1,1,3,1,2014,0.262,37.0,3.0,32.0,93.0
31692,Ángel Pagán#,33,SFG,133,551,512,55,134,21,3,3,37,12,4,32,93,0.262,0.303,0.332,0.635,75,170,12,1,0,6,0,2015,0.277,55.0,12.0,42.0,66.0
31693,Ángel Pagán#,34,SFG,129,543,495,71,137,24,5,12,55,15,4,42,66,0.277,0.331,0.418,0.750,102,207,11,0,0,3,1,2016,NaN,NaN,NaN,NaN,NaN

In [52]:
pitching

,Name,Age,Tm,W,L,W-L%,ERA,G,GS,GF,CG,SHO,SV,IP,H,R,ER,HR,BB,IBB,SO,HBP,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year,Nxt_ERA,Nxt_SO,Nxt_WHIP,Nxt_BB,Nxt_W,Nxt_SV
0,A.J. Achter,25,MIN,1,0,1.000,3.27,7,0,1,0,0,0,11.0,14,7,4,2,3,0,5,0,0,0,49,123,5.40,1.545,11.5,1.6,2.5,4.1,1.67,2014,6.75,14.0,1.350,6.0,0.0,0.0
1,A.J. Achter,26,MIN,0,1,0.000,6.75,11,0,4,0,0,0,13.1,12,10,10,4,6,1,14,0,0,0,58,62,6.28,1.350,8.1,2.7,4.1,9.5,2.33,2015,3.11,14.0,1.460,12.0,1.0,0.0
2,A.J. Achter,27,LAA,1,0,1.000,3.11,27,0,17,0,0,0,37.2,43,13,13,7,12,1,14,1,0,0,160,130,5.85,1.460,10.3,1.7,2.9,3.3,1.17,2016,NaN,NaN,NaN,NaN,NaN,NaN
3,A.J. Burnett,22,FLA,4,2,0.667,3.48,7,7,0,0,0,0,41.1,37,23,16,3,25,2,33,0,0,0,182,124,4.30,1.500,8.1,0.7,5.4,7.2,1.32,1999,4.79,57.0,1.500,44.0,3.0,0.0
4,A.J. Burnett,23,FLA,3,7,0.300,4.79,13,13,0,0,0,0,82.2,80,46,44,8,44,3,57,2,0,2,364,92,4.68,1.500,8.7,0.9,4.8,6.2,1.30,2000,4.05,128.0,1.315,83.0,11.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23611,Zane Smith*,33,PIT,10,8,0.556,3.27,25,24,0,2,1,0,157.0,162,67,57,18,34,7,57,0,0,2,645,132,4.55,1.248,9.3,1.0,1.9,3.3,1.68,1994,5.61,47.0,1.509,23.0,8.0,0.0
23612,Zane Smith*,34,BOS,8,8,0.500,5.61,24,21,0,0,0,0,110.2,144,78,69,7,23,1,47,1,1,0,484,87,3.73,1.509,11.7,0.6,1.9,3.8,2.04,1995,5.08,47.0,1.500,21.0,4.0,0.0
23613,Zane Smith*,35,PIT,4,6,0.400,5.08,16,16,0,1,1,0,83.1,104,53,47,7,21,4,47,4,1,0,368,87,4.04,1.500,11.2,0.8,2.3,5.1,2.24,1996,NaN,NaN,NaN,NaN,NaN,NaN
23614,Zeke Spruill,23,ARI,0,2,0.000,5.56,6,2,1,0,0,0,11.1,17,11,7,3,5,0,9,1,0,0,55,72,6.49,1.941,13.5,2.4,4.0,7.1,1.80,2013,3.57,14.0,1.368,4.0,1.0,0.0
23615,Zeke Spruill,24,ARI,1,1,0.500,3.57,6,1,1,0,0,0,22.2,27,11,9,0,4,0,14,1,0,0,99,106,2.56,1.368,10.7,0.0,1.6,5.6,3.50,2014,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
bat_na = batting.isna().sum()
bat_na

Name          0
Age           0
Tm            0
G             0
PA            0
AB            0
R             0
H             0
2B            0
3B            0
HR            0
RBI           0
SB            0
CS            0
BB            0
SO            0
BA            0
OBP           0
SLG           0
OPS           0
OPS+          0
TB            0
GDP           0
HBP           0
SH            0
SF            0
IBB           0
Year          0
Nxt_BA     4926
Nxt_RBI    4926
Nxt_HR     4926
Nxt_BB     4926
Nxt_SO     4926
dtype: int64

In [54]:
pitch_na = pitching.isna().sum()
pitch_na

Name           0
Age            0
Tm             0
W              0
L              0
W-L%           0
ERA            0
G              0
GS             0
GF             0
CG             0
SHO            0
SV             0
IP             0
H              0
R              0
ER             0
HR             0
BB             0
IBB            0
SO             0
HBP            0
BK             0
WP             0
BF             0
ERA+           0
FIP            0
WHIP           0
H9             0
HR9            0
BB9            0
SO9            0
SO/W           0
Year           0
Nxt_ERA     3883
Nxt_SO      3883
Nxt_WHIP    3883
Nxt_BB      3883
Nxt_W       3883
Nxt_SV      3883
dtype: int64

In [55]:
#####
# - I NEED TO REMOVE THE REMAINING NULL VALUES AS THEY ARE REFERENCING EITHER THE SEASON AFTER A PLAYERS LAST SEASON 
#   WHERE THEY DID NOT PLAY OR FOR THE 2023 SEASON WHICH HAS NOT YET OCCURED. IF I DO NOT REMOVE THESE ROWS IT 
#   WILL CAUSE ISSUES WITH MY ML MODEL WHEN I ATTEMPT TO RUN IT.
#####

batting = batting.dropna()
pitching = pitching.dropna()

In [56]:
bat_na = batting.isna().sum()
bat_na

Name       0
Age        0
Tm         0
G          0
PA         0
AB         0
R          0
H          0
2B         0
3B         0
HR         0
RBI        0
SB         0
CS         0
BB         0
SO         0
BA         0
OBP        0
SLG        0
OPS        0
OPS+       0
TB         0
GDP        0
HBP        0
SH         0
SF         0
IBB        0
Year       0
Nxt_BA     0
Nxt_RBI    0
Nxt_HR     0
Nxt_BB     0
Nxt_SO     0
dtype: int64

In [57]:
pitch_na = pitching.isna().sum()
pitch_na

Name        0
Age         0
Tm          0
W           0
L           0
W-L%        0
ERA         0
G           0
GS          0
GF          0
CG          0
SHO         0
SV          0
IP          0
H           0
R           0
ER          0
HR          0
BB          0
IBB         0
SO          0
HBP         0
BK          0
WP          0
BF          0
ERA+        0
FIP         0
WHIP        0
H9          0
HR9         0
BB9         0
SO9         0
SO/W        0
Year        0
Nxt_ERA     0
Nxt_SO      0
Nxt_WHIP    0
Nxt_BB      0
Nxt_W       0
Nxt_SV      0
dtype: int64

In [58]:
batting.to_csv('clean_batting.csv')
pitching.to_csv('clean_pitching.csv')

In [ ]:
#####
# - NOTES
#####

In [ ]:
#####
# - NOTES
#####